### ISSUE TITLE
Performance issue with Moment.js better with Date-fns

### ISSUE THREAD

**Issue by devzom** [thecodeorigin/nuxt-template#15]
Is not really an issue, just a suggest to use the package **date-fns** for date/datetime operation for better performance and smaller bundle.
Great repo/template, going to use it soon in big project :)

**Comment by bittermeatball** [comment]
@devzom thank you for your suggestion,  i will take it to consideration, for a general template, for me, i prefer a more popular library like `moment.js`, the project has `new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)` to minimize the bundle size 🎉
