### ISSUE TITLE
Update readme.md Drizzle link

### ISSUE THREAD

**Issue by devzom** [thecodeorigin/nuxt-template#43]
Used Drizzle link is invalid

`- [Drizzle ORM](https://drizzle.dev) for Database communication` -> 
`- [Drizzle ORM](https://orm.drizzle.team/) for Database communication`

**Comment by imrim12** [comment]
thanks for sticking with this project @devzom :)
very big improvement since the last time, also have a few friends contribute to this, feel free to add more feedback
